### ISSUE TITLE
Player Leader Board?

### ISSUE THREAD

**Issue by BASL-Webteam** [BigAppleSoftball/ratingsManager#14] opened 2015-04-22 00:37 UTC
I think we discussed creating a player Leader board from the Team Stats. I believe the api wouldn't allow it at the time. Possibly a future enhancement

**Comment by PaigePonzeka** [comment] 2015-04-25 13:53
Dupe of Division Stats, closing this one

**Closed by PaigePonzeka** 2015-04-25 13:53 UTC
